<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game [
  <!ELEMENT save (level)>
  <!ELEMENT level (id, name, path, validated, steps, time)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT validated (#PCDATA)>
  <!ELEMENT steps (#PCDATA)>
  <!ELEMENT time (#PCDATA)>
]>
<save>
  <level>
    <id>1</id>
    <name>Des débuts difficiles</name>
    <validated>false</validated>
    <steps>0</steps>
    <time>0</time>
  </level>
  <level>
    <id>2</id>
    <name>J'ai pas trouvé de nom pour le niveau 2</name>
    <validated>false</validated>
    <steps>0</steps>
    <time>0</time>
  </level>
  <level>
    <id>3</id>
    <name>Il faut vraiment trouver des noms pour les niveaux</name>
    <validated>false</validated>
    <steps>0</steps>
    <time>0</time>
  </level>
  <level>
    <id>4</id>
    <name>C'est le niveau 4</name>
    <validated>false</validated>
    <steps>0</steps>
    <time>0</time>
  </level>
</save>
